### ISSUE TITLE
登录用户问题

### ISSUE THREAD

**Issue by MingJ-Zhang** [caoqianming/django-vue-admin#31]
后端想得到当前登录的用户信息，需要怎么做呢。

**Comment by caoqianming** [comment]
认证以后直接request.user即可



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年8月16日(星期一) 上午8:50
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; 
主题: [caoqianming/django-vue-admin] 登录用户问题 (#31)





 
后端想得到当前登录的用户信息，需要怎么做呢。
 
—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by caoqianming** [comment]
ok
