### ISSUE TITLE
有人改了密码，登不上测试页面了

### ISSUE THREAD

**Issue by lilue** [caoqianming/django-vue-admin#34]

**Comment by caoqianming** [comment]
嗯，今天我重置一下数据库



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年9月6日(星期一) 上午9:13
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; 
主题: [caoqianming/django-vue-admin] 有人改了密码，登不上测试页面了 (#34)





 
—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
