### ISSUE TITLE
好像不支持局域网连接呀

### ISSUE THREAD

**Issue by Celading** [caoqianming/django-vue-admin#35]
琢磨了三天了，求大佬解答😭

**Comment by Celading** [comment]
没有错误代码，运行正常，就是在局域网其他电脑运行提示“服务器错误”

**Comment by caoqianming** [comment]
哦，前端接口地址改一下，重新打包



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年9月22日(周三) 下午4:19
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [caoqianming/django-vue-admin] 好像不支持局域网连接呀 (#35)




 
没有错误代码，运行正常，就是在局域网其他电脑运行提示“服务器错误”
 
—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by Celading** [comment]
是.env.developement的 VUE_APP_BASE_API = 'http://localhost:8000/api'这里吗

**Comment by Celading** [comment]
> 哦，前端接口地址改一下，重新打包
> […](#)
> ---原始邮件--- 发件人: ***@***.***&gt; 发送时间: 2021年9月22日(周三) 下午4:19 收件人: ***@***.***&gt;; 抄送: ***@***.******@***.***&gt;; 主题: Re: [caoqianming/django-vue-admin] 好像不支持局域网连接呀 (#35) 没有错误代码，运行正常，就是在局域网其他电脑运行提示“服务器错误” — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android.

大佬有没有比较详细的指点

**Comment by bldu** [comment]
请问是什么解决办法呢，新人求教

**Comment by caoqianming** [comment]
runserver的时候指定为你电脑的局域网ip，前端也对应改一下api请求地址



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年2月1日(周四) 晚上7:56
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [caoqianming/django-vue-admin] 好像不支持局域网连接呀 (#35)




 
请问是什么解决办法呢，新人求教
