### ISSUE TITLE
重写UserViewSet下的get_queryset()会报个警告，这个要怎么处理吗？

### ISSUE THREAD

**Issue by lilue** [caoqianming/django-vue-admin#36]
访问docs/时警告：

UserWarning: <class 'apps.system.views.UserViewSet'> is not compatible with schema generation
  "{} is not compatible with schema generation".format(view.__class__)
这里需要处理吗？是什么原因？我搜了一下没找到解决方法，来请教一下

**Comment by caoqianming** [comment]
我暂时也没处理，没啥影响



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年9月24日(周五) 中午11:53
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [caoqianming/django-vue-admin] 重写UserViewSet下的get_queryset()会报个警告，这个要怎么处理吗？ (#36)




 
访问docs/时警告：
 
UserWarning: <class 'apps.system.views.UserViewSet'&gt; is not compatible with schema generation
 "{} is not compatible with schema generation".format(view.class)
 这里需要处理吗？是什么原因？我搜了一下没找到解决方法，来请教一下
 
—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by lilue** [comment]
哦哦，好的
