### ISSUE TITLE
部署

### ISSUE THREAD

**Issue by MingJ-Zhang** [caoqianming/django-vue-admin#37]
如何部署到linux

**Comment by caoqianming** [comment]
步骤基本一样的



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年10月7日(周四) 中午1:25
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [caoqianming/django-vue-admin] 部署 (#37)




 
如何部署到linux
 
—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
