### ISSUE TITLE
预览地址后台密码不对

### ISSUE THREAD

**Issue by xyuer** [caoqianming/django-vue-admin#38]
有人估计改了密码么

**Comment by caoqianming** [comment]
嗯，一会我看一下，重置下数据库



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年10月19日(周二) 下午2:06
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [caoqianming/django-vue-admin] 预览地址后台密码不对 (Issue #38)




 
有人估计改了密码么
 
—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
