### ISSUE TITLE
预览地址admin用户密码错误

### ISSUE THREAD

**Issue by hczs** [caoqianming/django-vue-admin#40]

**Comment by caoqianming** [comment]
好了



------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "caoqianming/django-vue-admin"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年11月29日(星期一) 下午4:47
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[caoqianming/django-vue-admin] 预览地址admin用户密码错误 (Issue #40)





 
—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
